package com.miaoshaproject.miaosha.dao;

import com.miaoshaproject.miaosha.domain.Password;

public interface PasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Nov 11 15:49:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Nov 11 15:49:30 CST 2019
     */
    int insert(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Nov 11 15:49:30 CST 2019
     */
    int insertSelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Nov 11 15:49:30 CST 2019
     */
    Password selectByPrimaryKey(Integer id);

    Password selectByUserId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Nov 11 15:49:30 CST 2019
     */
    int updateByPrimaryKeySelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Nov 11 15:49:30 CST 2019
     */
    int updateByPrimaryKey(Password record);
}